<template>
  <div class="asset-stack">
    <section class="panel asset-panel sql-panel"><div class="panel-heading compact"><div><span class="eyebrow">DATA ASSET</span><h2>SQL 与清洗规则</h2></div><span class="asset-status">{{ sql ? 'READY' : 'WAITING' }}</span></div><div class="asset-tabs"><button :class="{active: tab === 'sql'}" @click="tab='sql'">生产 SQL</button><button :class="{active: tab === 'rules'}" @click="tab='rules'">清洗 Rules <b>{{ rules.length }}</b></button><button :class="{active: tab === 'sandbox'}" @click="tab='sandbox'">沙盒结果</button></div><div class="asset-content" v-if="tab === 'sql'"><pre v-if="sql"><code>{{ sql }}</code></pre><div v-else class="empty-state small"><span class="empty-icon">⌘</span><p>等待 SQL Agent 输出资产</p></div></div><div class="asset-content rules-grid" v-else-if="tab === 'rules'"><div v-for="rule in rules" :key="rule.id" class="rule-row"><b>{{ rule.id }}</b><span><strong>{{ rule.name }}</strong>{{ rule.rule }}</span><em>PASS</em></div></div><div class="asset-content" v-else><div v-if="sandbox" class="sandbox-summary"><div><span>状态</span><strong class="green">{{ sandbox.status }}</strong></div><div><span>预计行数</span><strong>{{ formatNumber(sandbox.compiled_rows) }}</strong></div><div><span>成本</span><strong>{{ sandbox.cost_seconds }}s</strong></div></div><pre v-if="sandbox" class="sample-code">{{ JSON.stringify(sandbox.sample, null, 2) }}</pre><div v-else class="empty-state small"><p>等待沙盒验证</p></div></div></section>
    <section class="panel asset-panel copy-panel"><div class="panel-heading compact"><div><span class="eyebrow">GROWTH ASSET</span><h2>A/B 文案演化</h2></div><span class="asset-status">{{ copy ? '2 VARIANTS' : 'WAITING' }}</span></div><div v-if="copy" class="copy-content"><div class="variant-switch"><button v-for="variant in copy.variants" :key="variant.id" :class="{active: variant.id === selectedVariant}" @click="selectedVariant = variant.id"><span>Variant {{ variant.id }}</span><strong>{{ Math.round(variant.score * 100) }} <small>预估点击</small></strong></button></div><article class="copy-card"><div class="copy-card-top"><span class="angle">{{ activeVariant.angle }}</span><span class="winner" v-if="copy.winner === activeVariant.id">WINNER</span></div><h3>{{ activeVariant.title }}</h3><p>{{ activeVariant.copy }}</p></article><div class="copy-foot"><span>对抗记录：红方生成 → 蓝方挑刺 → 红方 v2 交付</span><span>人群：{{ copy.audience }}</span></div></div><div v-else class="empty-state"><span class="empty-icon">✦</span><p>等待 Red / Blue Agent 生成对照组</p></div></section>
  </div>
</template>
<script setup>
import { computed, ref } from 'vue';
const props = defineProps({ sql: {type: String, default: ''}, rules: {type: Array, default: () => []}, sandbox: {type: Object, default: null}, copy: {type: Object, default: null} });
const tab = ref('sql'); const selectedVariant = ref('A');
const activeVariant = computed(() => props.copy?.variants?.find(item => item.id === selectedVariant.value) || props.copy?.variants?.[0] || { title: '', copy: '', angle: '', id: 'A', score: 0 });
const formatNumber = value => Number(value || 0).toLocaleString('zh-CN');
</script>
