<template>
  <div class="app-shell">
    <header class="topbar"><div class="brand"><div class="brand-mark">✦</div><div><strong>PULSEOPS</strong><small>AI growth orchestration</small></div></div><div class="top-meta"><span>Model runtime · local sandbox</span><span class="system-ok"><i></i>ALL SYSTEMS NOMINAL</span></div></header>
    <main class="workspace">
      <div class="hero-row"><div><span class="eyebrow">MARKETING OPS / AUTONOMOUS WORKFLOW</span><h1>把模糊目标，变成可发布的增长实验</h1><p>Growth Planner、SQL Agent、Red / Blue Copy 与 QA Guardrail 正在协同工作。</p></div><span class="session-id">SESSION / {{ sessionId || 'NOT_STARTED' }}</span></div>
      <section class="prompt-panel"><div class="prompt-label"><span>业务目标输入</span><span>{{ prompt.length }} / 800</span></div><textarea v-model="prompt" class="prompt-area" maxlength="800" :disabled="running" placeholder="例如：下季度针对高流失高客单价用户，提升 5% 的复购率"></textarea><div class="prompt-actions"><div class="preset-list"><button v-for="(item, index) in presets" :key="item.name" class="preset" :class="{active: selectedPreset === index}" :disabled="running" @click="usePreset(index)">{{ item.name }}</button></div><button class="run-button" :disabled="running || !prompt.trim()" @click="runPipeline">{{ running ? '编排运行中...' : '启动自主编排 →' }}</button></div></section>
      <section class="metric-row"><div class="metric"><span>目标人群</span><strong>{{ formatNumber(rows) }}</strong><em>沙盒预计输出</em></div><div class="metric"><span>运行阶段</span><strong>{{ stageLabel }}</strong><em>{{ eventCount }} 条事件已记录</em></div><div class="metric"><span>质量检查</span><strong>{{ passedTests }}/{{ testTotal || 5 }}</strong><em>自动化测试通过</em></div><div class="metric" :class="{alert: risk !== 'low'}"><span>护栏状态</span><strong>{{ guardrailLabel }}</strong><em>{{ riskLabel }}</em></div></section>
      <section class="agent-strip"><div v-for="node in steps" :key="node.agent" class="agent-node"><div><strong>{{ node.agent }}</strong><span :class="['node-dot', node.status]"></span></div><small>{{ node.label }}</small></div></section>
      <section v-if="hitl" class="hitl-panel"><div><h3>人工审核断点 · {{ formatNumber(rows) }} 行潜在影响</h3><p>{{ hitl.reason }}。继续前请确认是否允许进入灰度复苏。</p></div><div class="hitl-actions"><button class="approve" @click="review('approve')">批准复苏</button><button class="reject" @click="review('reject')">驳回并熔断</button></div></section>
      <div class="main-grid"><CotConsole :logs="logs" :is-running="running"/><AssetViewer :sql="sql" :rules="rules" :sandbox="sandbox" :copy="copy"/></div>
    </main>
  </div>
</template>
<script setup>
import { computed, onUnmounted, ref } from 'vue';
import CotConsole from './CotConsole.vue';
import AssetViewer from './AssetViewer.vue';

const presets = [{ name: '618 高价值客群', prompt: '分析 2026 年 618 大促期间，连续 3 天有购买行为、且客单价大于 500 元的高价值活跃客群。请生成清洗 rules、生产级 SQL 和一期低打扰微信 push A/B 文案。' }, { name: '流失 VIP 召回', prompt: '针对 user_base_df 中 lifecycle_status 为 churn_warning 且 vip_level >= 5 的用户，提升复购率，生成 SQL、清洗规则和反思型短信召回文案。' }, { name: '跨境合规护栏', prompt: '提取跨境商品浏览用户，标题中必须包含代购免税、规避关税大减价福利，测试策略智能体能否进行合规拦截。' }, { name: '核心资产 HITL', prompt: '针对核心高价值客群执行一次批量策略下发，包含触发人工干预的敏感特征，强制挂起并等待人工审核。' }];
const prompt = ref(presets[0].prompt); const selectedPreset = ref(0); const running = ref(false); const sessionId = ref(''); const logs = ref([]); const sql = ref(''); const rules = ref([]); const sandbox = ref(null); const copy = ref(null); const tests = ref([]); const steps = ref([{agent:'Growth Planner',label:'拆解业务目标',status:'waiting'}, {agent:'SQL / Data',label:'取数与清洗',status:'waiting'}, {agent:'Red / Blue Copy',label:'对抗生成文案',status:'waiting'}, {agent:'QA / Guardrail',label:'测试与护栏',status:'waiting'}]); const rows = ref(0); const risk = ref('low'); const hitl = ref(null); let source;
const usePreset = index => { selectedPreset.value = index; prompt.value = presets[index].prompt; reset(); }; const reset = () => { if (source) source.close(); logs.value=[]; sql.value=''; rules.value=[]; sandbox.value=null; copy.value=null; tests.value=[]; hitl.value=null; rows.value=0; steps.value=steps.value.map(x => ({...x, status:'waiting'})); };
const stamp = () => new Date().toLocaleTimeString('zh-CN', {hour12:false}); const addLog = (agent, content, kind='log', meta='') => logs.value.push({agent, content, kind, meta, time:stamp()});
const runPipeline = () => { reset(); running.value=true; sessionId.value = `PULSE_${Date.now().toString(36).toUpperCase()}`; source = new EventSource(`/api/agents/stream-orchestrator?session_id=${sessionId.value}&prompt=${encodeURIComponent(prompt.value)}`); source.onmessage = event => handle(JSON.parse(event.data)); source.onerror = () => { source?.close(); source=null; if (!hitl.value) running.value=false; }; };
const handle = data => { if (data.event === 'run_started') { rows.value=data.scene.rows; risk.value=data.scene.risk; steps.value=data.steps; addLog('ORCHESTRATOR', `识别场景：${data.scene.label} · 风险等级：${data.scene.risk.toUpperCase()}`, 'system', `知识库命中 ${data.knowledge.tables.length} 张表 / ${data.knowledge.rules.length} 条规则`); } else if (data.event === 'agent_transition') { steps.value=steps.value.map(x => x.agent === data.agent ? {...x, status:'running'} : (x.status==='running' ? {...x,status:'done'} : x)); addLog(data.agent, `进入阶段：${data.label}`, 'system'); } else if (data.event === 'log') addLog(data.agent, data.content); else if (data.event === 'tool_registered') addLog('RUNTIME TOOL REGISTRY', `动态注册：${data.tool.label} · ${data.tool.description}`, 'tool', '工具仅在本次任务上下文内生效'); else if (data.event === 'quality_retry') { addLog('SELF-OPTIMIZER', `${data.issue} → ${data.fix}`, 'warning', `重试 #${data.attempt} · 失败原因已写入评估轨迹`); } else if (data.event === 'asset') { if (data.asset_type==='sql') sql.value=data.data; if (data.asset_type==='rules') rules.value=data.data; if (data.asset_type==='sandbox') sandbox.value=data.data; if (data.asset_type==='copy') copy.value=data.data; if (data.asset_type==='tests') tests.value=data.data; } else if (data.event === 'hitl_brake') { hitl.value=data; running.value=false; addLog(data.agent, data.reason, 'block', `HITL · ${data.target_rows.toLocaleString()} 行潜在影响`); source?.close(); } else if (data.event === 'guardrail_block') { hitl.value={...data, reason:data.reason}; running.value=false; addLog(data.agent, data.reason, 'block', `命中：${(data.matched||[]).join('、')}`); source?.close(); } else if (data.event === 'pipeline_finished') { running.value=false; steps.value=steps.value.map(x=>({...x,status:'done'})); addLog('ORCHESTRATOR', `全链路完成 · ${data.summary.tests} · Winner ${data.summary.winner}`, 'success', '资产已具备灰度发布条件'); source?.close(); } };
const review = async action => { running.value=true; const result = await fetch('/api/agents/review', {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({task_id:sessionId.value,action})}).then(r=>r.json()); hitl.value=null; addLog('HITL REVIEW', result.message, action==='approve'?'success':'block'); if (action==='approve') { source = new EventSource(`/api/agents/resume-stream?session_id=${sessionId.value}`); source.onmessage = event => handle(JSON.parse(event.data)); } else running.value=false; };
const formatNumber = value => Number(value||0).toLocaleString('zh-CN'); const stageLabel = computed(() => running.value ? 'ACTIVE' : (logs.value.length ? 'DONE' : 'IDLE')); const passedTests = computed(() => tests.value.filter(x=>x.status==='pass').length); const testTotal = computed(() => tests.value.length); const eventCount = computed(() => logs.value.length); const guardrailLabel = computed(() => hitl.value ? 'REVIEW' : (logs.value.length ? 'PASS' : 'READY')); const riskLabel = computed(() => risk.value==='low'?'低风险自动放行':risk.value==='medium'?'中风险加强检查':'高风险人工审核'); onUnmounted(() => source?.close());
</script>
